cloudspannerecosystem/liquibase-spanner

pom.xml, src/test/java/liquibase/ext/spanner/AbstractMockServerTest.java, src/test/java/liquibase/ext/spanner/DatabaseChangeLog.java, src/test/java/liquibase/ext/spanner/SimpleMockServerTest.java
Adds a simple mock server for quick testing without the need to start the emulator or a real Spanner instance.
Depends on #5, so this should only be merged after that.
=> test: use mock server for testing

build.gradle
Gradle build was broken as it did not include all required test dependencies.
=> fix: fixes test failures in gradle

src/test/java/liquibase/ext/spanner/CreateIndexTest.java, src/test/resources/create-index-singers-first-and-last-name.spanner.yaml, src/test/resources/create-index-singers-first-name.spanner.yaml, src/test/resources/create-index-singers-last-name.spanner.yaml
The standard generator for `createIndex` already works for Cloud Spanner, so this change actually only adds tests for that change type.
This PR depends on #9 which should be merged first.
=> feat: add support for createIndex change type

src/test/java/liquibase/ext/spanner/DropTableTest.java, src/test/resources/drop-singers-table.spanner.yaml
The standard generator for dropTable already works for Cloud Spanner, so this change only adds a test for that change type.
This PR depends on #9 which should be merged first.
=> test: add tests for DropTable

src/test/java/liquibase/ext/spanner/DropIndexTest.java, src/test/resources/drop-singers-firstname-index-with-tablename.spanner.yaml, src/test/resources/drop-singers-lastname-index.spanner.yaml
The standard generator for dropIndex already works for Cloud Spanner, so this change only adds tests for that change type.
This PR depends on #9 which should be merged first.
=> test: add tests for DropIndex

src/main/java/liquibase/ext/spanner/SpannerAddPrimaryKeyGenerator.java, src/main/java/liquibase/ext/spanner/SpannerDropPrimaryKeyGenerator.java, src/test/java/liquibase/ext/spanner/AddDropPrimaryKeyTest.java, src/test/resources/add-primary-key-singers.spanner.yaml, src/test/resources/drop-primary-key-singers.spanner.yaml
Adding/dropping primary keys is not supported in Cloud Spanner.
=> feat: add validation errors for add/drop primary key

src/test/java/liquibase/ext/spanner/AddAutoIncrementTest.java, src/test/resources/add-auto-increment-singers.spanner.yaml
Auto increment is not supported for Cloud Spanner. This adds a test that verifies that those changes will cause a validation error and stop the migration.
=> test: add test for validation failure for auto increment

src/main/java/liquibase/ext/spanner/SpannerAddUniqueConstraintGenerator.java, src/main/java/liquibase/ext/spanner/SpannerDropUniqueConstraintGenerator.java, src/test/java/liquibase/ext/spanner/AddDropUniqueConstraintTest.java, src/test/resources/add-unique-constraint-singers.spanner.yaml, src/test/resources/drop-unique-constraint-singers.spanner.yaml
Cloud Spanner does not support unique constraints and unique indexes should be used instead. Those can also be created using Liquibase, so we should not automatically convert unique constraints to unique indices in a generator.
=> feat: add validation errors for add/drop unique constraint

src/main/java/liquibase/ext/spanner/SpannerRenameColumnGenerator.java, src/test/java/liquibase/ext/spanner/RenameColumnTest.java, src/test/resources/rename-column-singers.spanner.yaml
Cloud Spanner does not support renaming an existing column. This adds a validation error for those change types for Cloud Spanner databases.
=> feat: add validation error for rename column

src/main/java/liquibase/ext/spanner/SpannerAddDefaultValueGenerator.java, src/main/java/liquibase/ext/spanner/SpannerDropDefaultValueGenerator.java, src/test/java/liquibase/ext/spanner/AddDropDefaultValueTest.java, src/test/resources/add-default-value-singers.spanner.yaml, src/test/resources/drop-default-value-singers.spanner.yaml
Cloud Spanner does currently not support setting a default value for a column.
=> feat: add validation errors for default values

src/main/java/liquibase/ext/spanner/SpannerAddLookupTableChange.java, src/test/java/liquibase/ext/spanner/AddLookupTableTest.java, src/test/resources/add-lookup-table-singers-countries.spanner.yaml
Adds a generator for the `addLookupTable` change type. Cloud Spanner does not have any `CREATE TABLE AS SELECT ...` type statement, so it needs a custom generator.
=> feat: add generator for lookup table

.circleci/config.yml
Creating a new release (see the release created -- done through CircleCI, although I marked it as prerelease) fixes.
To create a new release:
- switch to master branch at HEAD
- apply a git tag of form N.N.N
- push tags
=> Circleci fix for marking releases

build.gradle, src/main/java/liquibase/ext/spanner/DecimalSpannerType.java, src/test/java/com/google/spanner/liquibase/LiquibaseTests.java, src/test/java/liquibase/ext/spanner/CreateTableTest.java, src/test/resources/create-table-with-all-liquibase-types-except-decimal.spanner.yaml, src/test/resources/create_table.spanner.sql
Changes -
- Decimal type was incorrectly DECIMAL Spanner type rather than NUMERIC
- Added create-all-types for emulator and real Spanner. Emulator does not support NUMERIC yet so needed a different version.
- Tested for NOT NULL, types, and PRIMARY keys.
- Adjusted existing types to test for column type, NOT NULL, and PRIMARY keys as well.
- Re-factored some testing code
=> Adding more tests with emulator and real spanner with one bug fix

build.gradle, src/main/java/liquibase/ext/spanner/CloudSpanner.java, src/main/java/liquibase/ext/spanner/SpannerCreateTableGenerator.java
Liquibase 4 uses Java ServiceLoader rather than a custom scanner previously. This commit supports Liquibase 4 *and* 3.
Changes:
- Support ServiceLoader by automatically generated services by scanning classes in Gradle. Run ServiceLoader prior to build or test.
- Use Apache Commons for join() to reduce dependency on Liquibase (it was renamed between 3 and 4).
- Use Liquibase-Package for Liquibase 3 support. This is the proper way it should have been done.
=> Liquibase 4 upgrade

src/main/java/liquibase/ext/spanner/SpannerModifyDataTypeGenerator.java, src/test/java/com/google/spanner/liquibase/LiquibaseTests.java, src/test/java/liquibase/ext/spanner/ModifyDataTypeTest.java, src/test/resources/modify-data-type-singers-lastname.spanner.yaml, src/test/resources/modify-data-type-singers-singerinfo.spanner.yaml
Cloud Spanner requires both the data type and NOT NULL constraint to be repeated when modifying a column. There is no specific SET / ALTER TYPE command needed.
=> feat: support modify data type

src/test/java/liquibase/ext/spanner/SetRemarksTest.java, src/test/resources/set-column-remarks.spanner.yaml, src/test/resources/set-table-remarks.spanner.yaml
Remarks are only supported by a fixed list of databases in Liquibase, so there is no need to add a custom generator.
=> test: verify that remarks are not supported

src/test/java/com/google/spanner/liquibase/LiquibaseTests.java, src/test/java/liquibase/ext/spanner/LoadDataTest.java, src/test/resources/data/description1.txt, src/test/resources/data/description2.txt, src/test/resources/data/description3.txt, src/test/resources/data/singerinfo1.txt, src/test/resources/data/singerinfo2.txt, src/test/resources/data/singerinfo3.txt, src/test/resources/load-data-singers.spanner.yaml, src/test/resources/singers.csv
Adds tests for the `loadData` change type. The change type is automatically supported by Cloud Spanner, but with a couple of caveats:
* Liquibase supports a `UUID` load type. That will generate and set a `java.util.UUID` parameter value, which is currently not supported by the Cloud Spanner JDBC driver.
* Liquibase automatically reads all timestamps in the default timezone of the system and does not support specifying a timezone in the CSV file. Cloud Spanner only stores timestamps without any timezone. That means that the actual timestamp that is inserted into the database will depend on the timezone of system where the update is executed.
The change type will automatically use Batch DML if the Liquibase option `usePreparedStatements` is set to true.
=> test: add tests for loadData change type

.circleci/config.yml
This enables Circle CI to execute unit tests for each PR, including PR's from forked repositories. It does not execute integration tests against real Spanner.
The current build fails because of the error that is fixed in #49 .
=> build: execute unit tests for each commit

build.gradle
This isn't a proper fix, however -- this is only necessary with 16.1.0, but not 16.0.0, and it isn't clear why!
I would prefer a different fix, but this change was necessary for the shadowJar to work properly with Liquibase. It will work with 16.0.0 -- this is only with 16.1.0 -- but it's hard to see what's the difference.
=> Resolved issue with some JARs not being included in the shadowJar.

build.gradle, src/main/resources/logback.xml
When running with the Spanner plugin gRPC was logging at a DEBUG level.
This change -
- Removes the logback dependency. It isn't clear why it is needed. It isn't needed when running as an extension, and I don't expect it's needed for tests?
- Apply a configuration for logback.xml (which seems to be used by Liquibase) that configures gRPC at INFO level.
=> Remove logback from shadowJar and configure default logging for gRPC

pom.xml, src/main/java/liquibase/ext/spanner/CloudSpanner.java, src/main/java/liquibase/ext/spanner/InsertWithSelectGenerator.java, src/main/java/liquibase/ext/spanner/SpannerInsertOrUpdateGenerator.java, src/test/java/com/google/spanner/liquibase/LiquibaseTests.java, src/test/java/liquibase/ext/spanner/LoadUpdateDataTest.java, src/test/resources/load-update-data-singers.spanner.yaml, src/test/resources/singers-update.csv
Adds support for the load-update-data change type. This change type normally uses an UPSERT / MERGE statement. Cloud Spanner does not support that for DML statements, and Liquibase does not support using anything else than SQL for this change type. That means that the change type for Cloud Spanner will always generate two statements for each row that will be inserted/updated:
1. An optional `INSERT` statement that will check whether the row already exists.
1. An `UPDATE` statement that always updates the row (even if it was just inserted).
The more efficient way to do this would be to use an `InsertOrUpdate` mutation in Cloud Spanner. There is however currently no way to trigger that through SQL.
=> feat: support load-update-data

src/main/java/liquibase/ext/spanner/SpannerMergeColumnsChange.java, src/test/java/com/google/spanner/liquibase/LiquibaseTests.java, src/test/java/liquibase/ext/spanner/MergeColumnsTest.java, src/test/resources/merge-singers-firstname-and-lastname.spanner.yaml
Adds support for the `mergeColumns` change type. The data from the original columns are copied to the new column using Partitioned DML. This ensures that it will work for columns of any size.
The tests for this change ran into a bug in the emulator that has been reported here: https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/issues/16
=> feat: add support for merge columns

build.gradle, pom.xml, src/test/resources/logback.xml
* Changes the group id to `cloudspannerecosystem` to match the repository name and the group id that has already been granted permission to publish to Maven.
* Adds the necessary plugins and additional information to the pom that is needed for Maven Central.
* Enables the emulator tests when testing using Maven (instead of Gradle) + reduces the log spamming during tests.
Request for creating a new project in Maven Central can be found here: https://issues.sonatype.org/browse/OSSRH-62903
=> chore: prepare publish to Maven Central

pom.xml
Description, organization and developers are required elements for publishing to Maven Central.
=> fix: add required information to pom for Maven central

src/main/java/liquibase/ext/spanner/CloudSpanner.java, src/main/java/liquibase/ext/spanner/datatype/ArrayOfBytesSpanner.java, src/main/java/liquibase/ext/spanner/datatype/ArrayOfStringSpanner.java, src/test/java/com/google/spanner/liquibase/LiquibaseTests.java, src/test/java/liquibase/ext/spanner/CreateTableTest.java, src/test/java/liquibase/ext/spanner/GenerateSnapshotTest.java, src/test/resources/create-table-with-all-liquibase-types.spanner.yaml
Generating a change log from an existing database would generate wrong type names in some cases:
- `INT64` (and others) would be generated as `INT64(19)` because Liquibase assumed that the type could have variable length.
- `ARRAY<STRING(len)>` and `ARRAY<BYTES(len)>` types would be generated with the length moved to the end of the type declaration (e.g. `ARRAY<STRING>(100)`), as Liquibase assumes that all data types that have a parameter will have the parameter at the end.
Fixes #75, #76 and #77 
cc @marcindyjas
=> fix: generateChangelog would generate wrong type names

src/main/resources/logback.xml
The Spanner Liquibase extension should not include a `logback.xml` configuration file in the default build.
Updates #74
=> fix: remove logback config from build

src/main/java/liquibase/ext/spanner/change/CreateTableChangeSpanner.java, src/main/java/liquibase/ext/spanner/sqlgenerator/CreateTableStatementSpanner.java, src/test/java/liquibase/ext/spanner/CreateMultipleTablesTest.java, src/test/java/liquibase/ext/spanner/CreateTableTest.java, src/test/resources/create-singers-table.spanner.yaml, src/test/resources/create-table-with-all-liquibase-types.spanner.yaml, src/test/resources/create-table-with-all-spanner-types.spanner.yaml, src/test/resources/create_table.spanner.yaml
Liquibase automatically adds a NotNullConstraint to all primary key columns, regardless whether these have been marked as nullable or not. Cloud Spanner supports nullable primary key columns. This change adds a custom CreateTable change and statement for Spanner that removes the automatically generated NotNullConstraint from primary key columns.
NotNullConstraints that are explicitly set on primary key columns are respected.
Fixes #83
=> fix: support nullable primary key columns

build.gradle, pom.xml, src/main/java/liquibase/ext/spanner/CloudSpanner.java, src/main/java/liquibase/ext/spanner/CloudSpannerConnection.java, src/main/java/liquibase/ext/spanner/sqlgenerator/CreateTableGeneratorSpanner.java, src/test/java/com/google/spanner/liquibase/LiquibaseTests.java, src/test/java/com/google/spanner/liquibase/TestHarness.java, src/test/java/liquibase/ext/spanner/AbstractMockServerTest.java, src/test/java/liquibase/ext/spanner/GenerateSnapshotTest.java, src/test/java/liquibase/ext/spanner/SimpleMockServerTest.java
- Updates the JDBC driver to version 2.0.
- Sets the user-agent string (technically: clientLibToken) to `sp-liq` to indicate that the requests are going through Liquibase.
- Re-factors the `LiquibaseTests` and `TestHarness` to no longer reuse the same JDBC connection for each test, as the `Liquibase` object is `AutoCloseable`, which means that each instance should preferably be opened and closed within one try-with-resources block when possible.
=> deps: update to jdbc driver version 2.0 and set user agent

.circleci/config.yml
Increase the timeout for CircleCI when executing the integration tests. This has timed out a couple of times during the nightly builds.
=> build: increase integration test timeout

.gitignore, README.md, samples/spanner-liquibase-spring-boot-sample/README.md, samples/spanner-liquibase-spring-boot-sample/pom.xml, samples/spanner-liquibase-spring-boot-sample/src/main/java/com/google/cloud/spanner/liquibase/sample/SampleSpringBootApplication.java, samples/spanner-liquibase-spring-boot-sample/src/main/resources/db/changelog/db.changelog-1.0.yaml, samples/spanner-liquibase-spring-boot-sample/src/main/resources/db/changelog/db.changelog-master.yaml
Adds a working sample application for using Liquibase with Cloud Spanner in a Spring Boot application.
See discussion in https://github.com/cloudspannerecosystem/liquibase-spanner/issues/74
=> docs: add sample for Spring Boot integration

README.md, build.gradle, pom.xml, src/main/java/liquibase/ext/spanner/sqlgenerator/CreateTableStatementSpanner.java
Bumps Liquibase to 4.10.0 and adds a new overwrite for `CreateTableStatement`, as an additional method for adding a primary key has been added in 4.10.0. This method needs to be overridden in Spanner in order to correctly configure nullable primary key constraints for Spanner.
This PR is the reason that a small code change is needed to support Liquibase 4.10.0: https://github.com/liquibase/liquibase/pull/2752
=> deps: bump Liquibase to 4.10.0

limitations.md
Cloud Spanner now supports `DEFAULT` values, so this limitation can be removed.
=> docs: remove DEFAULT values limitation

src/main/java/liquibase/ext/spanner/snapshotgenerator/IndexSnapshotGeneratorSpanner.java, src/test/java/liquibase/ext/spanner/GenerateSnapshotTest.java, src/test/java/liquibase/ext/spanner/JdbcMetadataQueries.java
Adds support for taking a snapshot of an index with a STORING column clause. These failed because Liquibase assumes that the ordinal position of a column would always be non-null. In Cloud Spanner, index columns in a STORING clause have a null value for their ordinal position.
Note that the STORING clause is not generated by Liquibase, as Liquibase itself does nothing with that part of an index. This could be added to a custom index generator for Cloud Spanner in a separate PR.
Fixes #159
=> fix: support snapshotting indexes with include columns

build.gradle, pom.xml, src/test/java/com/google/spanner/liquibase/TestHarness.java
Updates the dependencies for testing using the emulator to the latest. This also includes always using the latest version of the emulator for tests. The startup time of the emulator based tests is optmized by adding a wait-for for the listening port of the emulator, instead of relying on a 10 second startup-wait-time and an error being returned for a non-existing URL.
=> deps: bump emulator version to latest and optimize startup

.github/workflows/units.yaml, pom.xml
Bumps the Liquibase test harness version to 1.0.9 and aligns all other relevant test dependencies with the versions that are required for that. Note that the test harness version 1.0.9 no longer works with Java 8, and requires at least Java 11 to run. This change therefore also adds a build profile that is only activated for Java 8 and that excludes running the Liquibase test harness tests. The tests are run on Java 11 and higher.
=> deps: update Liquibase test harness to 1.0.9

README.md
Improve the documentation for DDL batches by adding a section at the beginning of the README. Also fixes the link to the SQL statements that should be used to define DDL batches.
Fixes #119
=> docs: improve documentation and recommendation for DDL batches

.circleci/config.yml
Use a pinned Unbuntu image version to ensure that we get JDK8.
=> build: use pinned Ubuntu version for JDK8

src/main/java/liquibase/ext/spanner/sqlgenerator/CreateSequenceGeneratorSpanner.java, src/main/java/liquibase/ext/spanner/sqlgenerator/DropSequenceGeneratorSpanner.java, src/test/java/com/google/spanner/liquibase/LiquibaseTests.java, src/test/java/liquibase/ext/spanner/sqlgenerator/CreateDropSequenceTest.java, src/test/resources/create-sequence.spanner.yaml
Adds support for creating and dropping bit-reversed sequences. Renaming a sequence is still not supported.
The minValue and maxValue properties in Liquibase do not have a corresponding property in Cloud Spanner, but at the same time, Cloud Spanner has skip_range_min and skip_range_max, which are not available in Liquibase. The minValue van maxValue properties in Liquibase are therefore mapped to the skip-range values in Cloud Spanner.
=> feat: support bit-reversed sequences

src/main/java/liquibase/ext/spanner/CloudSpanner.java, src/test/java/liquibase/ext/spanner/CreateTableTest.java, src/test/resources/create-singers-table.spanner.yaml
Spanner GoogleSQL uses backticks for quoting identifiers. Liquibase by default uses double quotes, and the Spanner Liquibase driver did not override this default.
Fixes #230
=> fix: use backticks for quoting identifiers

pom.xml, src/main/java/liquibase/ext/spanner/CloudSpanner.java, src/test/java/liquibase/ext/spanner/AbstractMockServerTest.java
The Spanner JDBC driver will start to use multiplexed sessions by default. This means that the (mock) server will receive CreateSession RPCs. These should be ignored when looking for the correct client lib header.
The JDBC driver will also start reporting that it supports named schemas. This will trigger a different getTables(..) call from Liquibase, as it thinks that the DATABASECHANGELOG tables can be in any schema.
=> test: prepare tests for mux sessions and named schemas

src/main/java/liquibase/ext/spanner/sqlgenerator/DeleteGeneratorSpanner.java, src/main/java/liquibase/ext/spanner/sqlgenerator/UpdateGeneratorSpanner.java, src/test/java/com/google/spanner/liquibase/LiquibaseTests.java, src/test/java/liquibase/ext/spanner/SqlTest.java
Spanner requires that all UPDATE and DELETE statements contain a WHERE clause as safety precaution against accidental updates and deletes. Liquibase however by default generates UPDATE and DELETE statements without a WHERE clause if none has been specified. The Spanner Liquibase provider therefore now adds custom generators for those statements that automatically add a `WHERE true` clause to statements that do not have a WHERE clause.
The `clear-checksums` command (https://docs.liquibase.com/commands/utility/clear-checksums.html) generated such an update statement, and would therefore fail with an error like this:
```
INVALID_ARGUMENT: com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException:  
INVALID_ARGUMENT: UPDATE must have a WHERE clause [at 1:1]
UPDATE …
```
=> fix: clearCheckSums generated invalid SQL

src/main/java/liquibase/ext/spanner/CloudSpanner.java, src/test/resources/liquibase/harness/data/changelogs/cloudspanner/loadUpdateData.csv, src/test/resources/liquibase/harness/data/changelogs/cloudspanner/loadUpdateData.xml, src/test/resources/liquibase/harness/data/expectedResultSet/cloudspanner/loadUpdateData.json, src/test/resources/liquibase/harness/data/expectedSql/cloudspanner/loadUpdateData.sql
To ensure predictable behavior, adjustments were made to handle timezone differences appropriately and align Liquibase's behavior with Cloud Spanner's expectations.
=> Handle Timezone Differences in Liquibase for Cloud Spanner

src/test/java/liquibase/ext/spanner/CreateTableWithGeneratedColumns.java, src/test/resources/create-table-with-generated-column.spanner.yaml, src/test/resources/liquibase/harness/change/changelogs/cloudspanner/createTableWithGeneratedColumn.xml, src/test/resources/liquibase/harness/change/expectedSnapshot/cloudspanner/createTableWithGeneratedColumn.json, src/test/resources/liquibase/harness/change/expectedSql/cloudspanner/createTableWithGeneratedColumn.sql
This PR introduces a test for generated (computed) columns in Liquibase changelogs.
Added a test to verify the correct handling of computed columns.
Using for computed="true" and Type in the changelog.
Ensured the generated SQL correctly reflects the computed column definition.
=> test: add test for Generated Column in Liquibase Changelog

src/main/java/liquibase/ext/spanner/snapshotgenerator/ColumnSnapshotGeneratorSpanner.java, src/test/java/liquibase/ext/spanner/AbstractMockServerTest.java
The Spanner Liquibase provider executes an extra query to get the column default value, as the Spanner JDBC driver does not include that in the metadata it returns.
This will be fixed in https://github.com/googleapis/java-spanner-jdbc/pull/1937
=> chore: register a default mock result for column defaults

src/main/java/liquibase/ext/spanner/CloudSpanner.java, src/main/java/liquibase/ext/spanner/ICloudSpanner.java, src/main/java/liquibase/ext/spanner/sqlgenerator/CreateDatabaseChangeLogLockTableGeneratorSpanner.java, src/main/java/liquibase/ext/spanner/sqlgenerator/CreateDatabaseChangeLogTableGeneratorSpanner.java, src/test/java/liquibase/ext/spanner/sqlgenerator/CreateDatabaseChangeLogLockTableGeneratorSpannerTest.java, src/test/java/liquibase/ext/spanner/sqlgenerator/CreateDatabaseChangeLogTableGeneratorSpannerTest.java
This PR introduces the getDialect() method to both SpannerDatabase and PostgreSqlSpannerDatabase implementations, enabling dialect-aware SQL generation and feature toggling.
Changes:
Implemented getDialect() method returning GOOGLE_STANDARD_SQL or POSTGRESQL as appropriate
Updated related logic to retrieve dialect in SQL generators and changelog handlers
Implement create system Liquibase tables for both dialect  support
=> chore: add getDialect() method

pom.xml, src/main/java/liquibase/ext/spanner/sqlgenerator/CreateDatabaseChangeLogTableGeneratorSpanner.java
Spanner does not allow trailing semicolons in DDL statements. Previously, these were automatically
removed by the Spanner client library. This is no longer the case, so we need to remove it from
the Liquibase code for this to work with the latest Spanner client.
Fixes #481
=> fix: remove trailing semicolon in create table databasechangelog
