cloudspannerecosystem/liquibase-spanner

src/main/java/liquibase/ext/spanner/BigIntTypeSpanner.java
src/main/java/liquibase/ext/spanner/BoolTypeSpanner.java
src/main/java/liquibase/ext/spanner/CloudSpanner.java
src/main/java/liquibase/ext/spanner/IntTypeSpanner.java
src/main/java/liquibase/ext/spanner/SpannerCreateDatabaseChangeLogLockTableGenerator.java
src/main/java/liquibase/ext/spanner/SpannerCreateDatabaseChangeLogTableGenerator.java
src/main/java/liquibase/ext/spanner/SpannerInitializeChangeLogLockTableGenerator.java
src/main/java/liquibase/ext/spanner/SpannerStandardChangeLogHistoryService.java
src/main/java/liquibase/ext/spanner/TimestampTypeSpanner.java
src/main/java/liquibase/ext/spanner/VarcharTypeSpanner.java
src/test/java/com/google/spanner/liquibase/LiquibaseTests.java
src/test/java/com/google/spanner/liquibase/TestHarness.java
src/test/java/liquibase/ext/spanner/AbstractMockServerTest.java
src/test/java/liquibase/ext/spanner/DatabaseChangeLog.java
src/test/java/liquibase/ext/spanner/SimpleMockServerTest.java
src/test/java/liquibase/ext/spanner/VarcharTypeSpannerTest.java

Ran `mvn com.coveo:fmt-maven-plugin:format` on all source files to adhere to the standard Google formatting style for Java.

chore: run formatter on all code

---

src/test/java/com/google/spanner/liquibase/TestHarness.java
src/test/java/liquibase/ext/spanner/AbstractMockServerTest.java

Cleanup and close resources after tests finish.
Also use a partial statement result on the mock server for acquiring a lock, as the custom generator that was added by the test did not work when it was used in combination with the emulator tests. The reason for that was that the emulator tests were executed first, which initialized Liquibase, and adding additional generators after Liquibase has already been initialized does not work.
This should (finally) fix the gradle build errors.

fix: cleanup test resources and use partial statement

---

src/test/java/liquibase/ext/spanner/AddColumnTest.java
src/test/resources/add-singer-to-concerts-table.spanner.yaml
src/test/resources/add-singerinfo-to-singers-table.spanner.yaml
src/test/resources/add-track-and-lyrics-to-songs-table.spanner.yaml

Adds tests for the `addColumn` change type.
Depends on #9.

test: add tests for AddColumn

---

src/test/java/liquibase/ext/spanner/DropColumnTest.java
src/test/resources/drop-column-singerinfo.spanner.yaml
src/test/resources/drop-columns-track-and-lyrics.spanner.yaml

Adds tests for the `dropColumn` change type.
Depends on #9.

test: add tests for DropColumn

---

src/main/java/liquibase/ext/spanner/SpannerCreateProcedureGenerator.java
src/main/java/liquibase/ext/spanner/SpannerDropProcedureGenerator.java
src/test/java/liquibase/ext/spanner/CreateDropProcedureTest.java
src/test/resources/create-procedure.spanner.yaml
src/test/resources/drop-procedure.spanner.yaml

Adds validation for create/drop procedure changes.

feat: stop create/drop procedure changes

---

src/main/java/liquibase/ext/spanner/SpannerCreateViewGenerator.java
src/main/java/liquibase/ext/spanner/SpannerDropViewGenerator.java
src/test/java/liquibase/ext/spanner/CreateDropViewTest.java
src/test/resources/create-view.spanner.yaml
src/test/resources/drop-view.spanner.yaml

Add validation errors for creating/dropping views.

feat: add validation errors for views

---

src/main/java/liquibase/ext/spanner/SpannerCreateSequenceGenerator.java
src/main/java/liquibase/ext/spanner/SpannerDropSequenceGenerator.java
src/test/java/liquibase/ext/spanner/CreateDropSequenceTest.java
src/test/resources/create-sequence.spanner.yaml
src/test/resources/drop-sequence.spanner.yaml

Adds generators and errors for sequences.

feat: add errors for sequences

---

src/main/java/liquibase/ext/spanner/SpannerDropAllForeignKeyConstraintsChange.java
src/test/java/com/google/spanner/liquibase/LiquibaseTests.java
src/test/java/liquibase/ext/spanner/DropAllForeignKeysTest.java
src/test/resources/drop-all-foreign-key-constraints-singers.spanner.yaml
src/test/resources/drop-foreign-key.spanner.yaml

Adds support for dropping all foreign keys and tests for dropping single foreign keys.

feat: add support for drop (all) FKs

---

pom.xml
src/main/java/liquibase/ext/spanner/CloudSpanner.java

The Maven build did not include service definition files.

fix: include service files in Maven build

---

build.gradle

Upgraded test containers from 1.15.0 to 1.15.1.
See https://github.com/testcontainers/testcontainers-java/issues/3166 for details.

This is to fix an issue with recent Docker on OS/X and test containers.

---

src/test/java/liquibase/ext/spanner/CreateMultipleTablesTest.java
src/test/resources/create-multiple-tables.spanner.yaml

Adds a test that shows how to use DDL batching within one change set.

test: add test for DDL batching

---

src/main/java/liquibase/ext/spanner/snapshotgenerator/ForeignKeySnapshotGeneratorSpanner.java
src/test/java/com/google/spanner/liquibase/LiquibaseTests.java

`INTERLEAVED TABLES` in Cloud Spanner are included in the foreign keys in the JDBC metadata. Liquibase therefore also includes these in a snapshot of a database, although these are not real foreign keys. This PR removes the generation of these foreign keys from snapshots.
This does not include a change to correct the `CREATE TABLE` change that is generated from the snapshot. These should ideally also include the `INTERLEAVE IN PARENT` sql fragment that is needed to create a child table.
Towards #78

fix: do not generate interleaved table as FK in snapshot

---

README.md
pom.xml

Updated documentation  -- extension is no longer beta.

No longer beta.

---

pom.xml

chore: use Google-specific endpoint

---

build.gradle
pom.xml
src/main/java/liquibase/ext/spanner/CloudSpanner.java
src/main/java/liquibase/ext/spanner/sqlgenerator/CreateTableStatementSpanner.java

Updates Liquibase to version 4.6.1
cc @thiagotnunes and @ansh0l

deps: update to version 4.6.1

---

README.md
build.gradle
pom.xml

deps: bump Liquibase to 4.9.0

---

src/main/java/liquibase/ext/spanner/sqlgenerator/CreateDatabaseChangeLogLockTableGeneratorSpanner.java
src/main/java/liquibase/ext/spanner/sqlgenerator/CreateDatabaseChangeLogTableGeneratorSpanner.java
src/test/java/liquibase/ext/spanner/sqlgenerator/CreateDatabaseChangeLogLockTableGeneratorSpannerTest.java
src/test/java/liquibase/ext/spanner/sqlgenerator/CreateDatabaseChangeLogTableGeneratorSpannerTest.java

This change adds support for customization of changelog and changeloglock table names. (see issue #121 )

#121 Added support for configured databasechangelog/lock table names.

---

.github/dependabot.yml

Configure dependabot for automatic dependency updates.

deps: configure dependabot

---

pom.xml

Bumps the minor version number.

chore: bump version number

---

src/test/java/liquibase/ext/spanner/SqlTest.java
src/test/resources/sql.yaml

Adds a test that shows how to insert data using a set of SQL statements.
Updates #308

test: add test for inserting data with SQL

---

src/test/java/liquibase/ext/spanner/CreateChangeStreamTest.java
src/test/java/liquibase/ext/spanner/CreateInterleaveTableTest.java
src/test/java/liquibase/ext/spanner/CreateRowDeletionPolicyTest.java
src/test/resources/create-change-stream.spanner.yaml
src/test/resources/create-interleave-table.spanner.yaml
src/test/resources/create-row-deletion-policy.spanner.yaml

This PR introduces test coverage for additional  features in Cloud Spanner:
Table Interleaving: Verifies correct handling of interleaved tables in Liquibase.
Row Deletion Policies: Ensures Liquibase correctly applies and manages row deletion policies.
Change Streams: Tests the configuration and management of change streams through Liquibase.

test: Add Tests for Table Interleaving, Row Deletion Policies, and Change Streams in Liquibase
